### ISSUE TITLE
If the detection doesn't work, please make a ticket on GitHub.

### ISSUE THREAD

**Issue by calang000** [andro2157/DiscordTokenProtector#88]
After updating discord, the program cannot locate the token. So I can't use it. I already uninstalled my discord and also the program and installed it again. but it did not work out

![image](https://github.com/andro2157/DiscordTokenProtector/assets/90231560/745ad677-3053-429a-9fbe-5694ed5a91a2)

**Comment by GuardianN06** [comment]
You can get your token manually and paste it in

**Comment by calang000** [comment]
![image](https://github.com/andro2157/DiscordTokenProtector/assets/90231560/da8f75ba-538e-4b5c-8958-0df5a1a72c6e)
I did it. but it doesn't solve the problem. since the application remains in 'injecting payload' . I don't know what to do anymore):

**Comment by GuardianN06** [comment]
I think your anti-virus is stopping it. Go into Defender or your Anti-virus, and put an exclusion on "C:\Users\<YourUser>\AppData\Roaming\DiscordTokenProtector"
This should solve the issue you have

**Comment by calang000** [comment]
![image](https://github.com/andro2157/DiscordTokenProtector/assets/90231560/f16eacdc-28d1-4575-9930-65ed5f8f1898)
didn't solve my problem)

**Comment by GuardianN06** [comment]
Maybe try removing the cache in roaming, delete these files and try again:

cache folder
config.json
secure.dat

and also, logfile would be good to send :)

**Comment by calang000** [comment]
[logging.log](https://github.com/andro2157/DiscordTokenProtector/files/15285129/logging.log)


I deleted the files you listed. but with the same problem!

I attached the log file you requested


![image](https://github.com/andro2157/DiscordTokenProtector/assets/90231560/0692f636-bf4b-4af5-995b-4bfb656fe7fb)

**Comment by GuardianN06** [comment]
I got no idea what's wrong, maybe the owner might help!

**Comment by calang000** [comment]
I don't know the owner is active here. Is there any way to contact him?

**Comment by ElectroYModz** [comment]
it's because it wasn't built for discord x64 but it was for x86 and discord now since not long ago downloads x64 by default

if you want to download x86 here: https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86

Edit: nvm doesn't seem to be the issue so most likely a discord update

**Comment by calang000** [comment]
right. I did this, but it didn't solve my problem):  


I hope the developer fixes this

**Comment by devkarlos** [comment]
> it's because it wasn't built for discord x64 but it was for x86 and discord now since not long ago downloads x64 by default
> 
> if you want to download x86 here: https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86
> 
> Edit: nvm doesn't seem to be the issue so most likely a discord update

You can be right. This seems to be an issue.

**Comment by KillaMeep** [comment]
Another bump to this. Same issue.

**Comment by GlitchedCod** [comment]
Same issue, maybe, just maybe, Discord finally fix that issue !

**Comment by arianwen27** [comment]
![image](https://github.com/andro2157/DiscordTokenProtector/assets/47794936/44dfc0ec-2578-4b4a-b261-d90b1d5b443c)
stuck at the same spot as the original poster of this issue. I can't work out how to get my token to manually paste it in. Any help?

**Comment by arianwen27** [comment]
Wanted to give this project a try, hopefully it gets 64 bit support soon
